In [1]:
import pandas

In [3]:
dataset=pandas.read_csv(r"E:\Data Analisys\Udemy.csv")

In [4]:
dataset

,id,title,url,is_paid,num_subscribers,avg_rating,avg_rating_recent,rating,num_reviews,is_wishlisted,num_published_lectures,num_published_practice_tests,created,published_time,discount_price__amount,discount_price__currency,discount_price__price_string,price_detail__amount,price_detail__currency,price_detail__price_string
0,762616,The Complete SQL Bootcamp 2020: Go from Zero t...,/course/the-complete-sql-bootcamp/,True,295509,4.66019,4.67874,4.67874,78006,False,84,0,2016-02-14T22:57:48Z,2016-04-06T05:16:11Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
1,937678,Tableau 2020 A-Z: Hands-On Tableau Training fo...,/course/tableau10/,True,209070,4.58956,4.60015,4.60015,54581,False,78,0,2016-08-22T12:10:18Z,2016-08-23T16:59:49Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
2,1361790,PMP Exam Prep Seminar - PMBOK Guide 6,/course/pmp-pmbok6-35-pdus/,True,155282,4.59491,4.59326,4.59326,52653,False,292,2,2017-09-26T16:32:48Z,2017-11-14T23:58:14Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
3,648826,The Complete Financial Analyst Course 2020,/course/the-complete-financial-analyst-course/,True,245860,4.54407,4.53772,4.53772,46447,False,338,0,2015-10-23T13:34:35Z,2016-01-21T01:38:48Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
4,637930,An Entire MBA in 1 Course:Award Winning Busine...,/course/an-entire-mba-in-1-courseaward-winning...,True,374836,4.47080,4.47173,4.47173,41630,False,83,0,2015-10-12T06:39:46Z,2016-01-11T21:39:33Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13603,3005408,מושגים בסיסיים באופציות חלק ב,/course/1-ndgzhu/,False,47,0.00000,0.00000,0.00000,0,False,6,0,2020-04-15T10:20:17Z,2020-04-23T02:06:55Z,NaN,NaN,NaN,NaN,NaN,NaN
13604,3467284,Programa de Integridade,/course/iaudit_programa_de_integridade/,False,19,0.00000,0.00000,0.00000,0,False,5,0,2020-09-01T17:57:15Z,2020-09-03T15:26:47Z,NaN,NaN,NaN,NaN,NaN,NaN
13605,3368222,Goodwill and Method of Calculating Goodwill (A...,/course/goodwill-and-method-of-calculating-goo...,False,47,0.00000,0.00000,0.00000,0,False,5,0,2020-07-27T02:29:18Z,2020-07-31T12:14:40Z,NaN,NaN,NaN,NaN,NaN,NaN
13606,3211345,Poderoso Investidor,/course/poderoso-investidor/,False,48,0.00000,0.00000,0.00000,0,False,13,0,2020-06-07T01:29:53Z,2020-07-15T10:35:38Z,NaN,NaN,NaN,NaN,NaN,NaN
13607,2935720,Acabou a Previdência e agora? - Volume 03,/course/acabou-a-previdencia-e-agora-volume-03/,True,0,0.00000,0.00000,0.00000,0,False,14,0,2020-03-30T19:10:58Z,2020-04-02T16:33:32Z,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13608 entries, 0 to 13607
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            13608 non-null  int64
 1   title                         13608 non-null  object
 2   url                           13608 non-null  object
 3   is_paid                       13608 non-null  bool
 4   num_subscribers               13608 non-null  int64
 5   avg_rating                    13608 non-null  float64
 6   avg_rating_recent             13608 non-null  float64
 7   rating                        13608 non-null  float64
 8   num_reviews                   13608 non-null  int64
 9   is_wishlisted                 13608 non-null  bool
 10  num_published_lectures        13608 non-null  int64
 11  num_published_practice_tests  13608 non-null  int64
 12  created                       13608 non-null  object
 13  published_time                13608 non-null  object
 14  discount_price__amount        12205 non-null  float64
 15  discount_price__currency      12205 non-null  object
 16  discount_price__price_string  12205 non-null  object
 17  price_detail__amount          13111 non-null  float64
 18  price_detail__currency        13111 non-null  object
 19  price_detail__price_string    13111 non-null  object
dtypes: bool(2), float64(5), int64(5), object(8)
memory usage: 1.9+ MB

In [7]:
dataset.sort_values("title", axis=0, ascending=True)

,id,title,url,is_paid,num_subscribers,avg_rating,avg_rating_recent,rating,num_reviews,is_wishlisted,num_published_lectures,num_published_practice_tests,created,published_time,discount_price__amount,discount_price__currency,discount_price__price_string,price_detail__amount,price_detail__currency,price_detail__price_string
6773,2235670,"! Risk Management in Projects, Programs and Po...",/course/leading-risk-management-in-projects-pr...,True,78,4.50000,4.47460,4.47460,14,False,155,0,2019-02-23T00:07:04Z,2019-04-16T18:32:47Z,455.0,INR,₹455,2560.0,INR,"₹2,560"
12583,2478310,"""BLACK HONEY"" Estrategia de SCALPING para el DAX",/course/black-honey-aprende-mi-estrategia-de-s...,True,23,4.57143,4.57099,4.57099,7,False,11,0,2019-07-26T09:32:03Z,2019-08-09T20:55:50Z,455.0,INR,₹455,4160.0,INR,"₹4,160"
13262,2613304,"""Bitcoin für Best Ager""",/course/bitcoin-fuer-best-ager/,True,8,0.00000,0.00000,0.00000,0,False,23,0,2019-10-18T16:20:55Z,2019-10-27T18:55:12Z,455.0,INR,₹455,1920.0,INR,"₹1,920"
7488,335586,"""Do"", Innovation, Product Design and Value Pro...",/course/do-innovation-and-value-proposition/,True,62,4.10000,3.86951,3.86951,10,False,19,0,2014-11-04T11:16:53Z,2015-08-20T22:38:30Z,NaN,NaN,NaN,12480.0,INR,"₹12,480"
11666,572048,"""Financial Emergency Preparation & Recovery"" w...",/course/disasterdollars/,False,3280,4.35000,4.16448,4.16448,47,False,11,0,2015-08-03T03:17:52Z,2015-08-03T21:39:19Z,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13120,1232374,飛岡健 経済の秘密解明講座vol.2,/course/vol2-arm/,True,6,5.00000,5.00000,5.00000,1,False,10,0,2017-05-28T03:48:53Z,2017-06-02T01:20:35Z,455.0,INR,₹455,1600.0,INR,"₹1,600"
13584,1653752,"바이낸스 거래소 사용법 - 가입,입금,출금,거래방법 완벽 가이드",/course/how-to-trade-on-binance/,False,214,4.75000,4.85839,4.85839,2,False,13,0,2018-04-19T10:42:25Z,2018-04-23T13:33:41Z,NaN,NaN,NaN,NaN,NaN,NaN
13183,1721938,쉽게 배우는 해운 시황의 이해,/course/ldikhhfv/,True,2,0.00000,0.00000,0.00000,0,False,19,0,2018-05-30T06:09:52Z,2018-06-29T15:21:33Z,455.0,INR,₹455,1280.0,INR,"₹1,280"
12184,1470794,（適用台灣股市）官股行庫操作分析研判方法（盤勢多空判斷法之一）,/course/hsung-govmoney-1/,True,107,4.45000,4.54398,4.54398,33,False,11,0,2017-12-15T15:20:02Z,2018-01-22T12:59:33Z,NaN,NaN,NaN,1920.0,INR,"₹1,920"
12026,639126,６時間でインターバンク市場を攻略！最短距離でトレード基礎力,/course/startforex/,True,503,4.30000,4.32800,4.32800,65,False,54,0,2015-10-13T11:02:02Z,2015-11-10T00:22:05Z,455.0,INR,₹455,1280.0,INR,"₹1,280"

In [9]:
dataset_id_sort = dataset.sort_values('id', axis=0, ascending=True)

In [10]:
dataset_id_sort

,id,title,url,is_paid,num_subscribers,avg_rating,avg_rating_recent,rating,num_reviews,is_wishlisted,num_published_lectures,num_published_practice_tests,created,published_time,discount_price__amount,discount_price__currency,discount_price__price_string,price_detail__amount,price_detail__currency,price_detail__price_string
686,2762,Simple Strategy for Swing Trading the Stock Ma...,/course/swing-trading-the-stock-market/,True,2268,4.21642,4.22936,4.22936,674,False,8,0,2010-04-14T21:32:46Z,2010-04-14T16:32:46Z,468.0,INR,₹468,2560.0,INR,"₹2,560"
1191,8075,How to Create an Awesome Demo Video for Your B...,/course/how-to-create-awesome-demo-videos/,True,10616,3.90000,3.88013,3.88013,326,False,91,0,2011-06-14T04:10:52Z,2011-07-06T14:06:34Z,500.0,INR,₹500,9280.0,INR,"₹9,280"
856,8467,The Lean Startup,/course/the-lean-startup/,True,4591,3.85294,3.78761,3.78761,512,False,6,0,2011-07-09T01:22:49Z,2011-07-11T06:29:02Z,455.0,INR,₹455,2560.0,INR,"₹2,560"
885,8849,Speak Up! Stand Out and be HAPPY,/course/speak-up/,True,7451,4.42857,4.44269,4.44269,492,False,26,0,2011-07-29T23:51:41Z,2011-08-22T01:55:25Z,455.0,INR,₹455,2880.0,INR,"₹2,880"
3677,9521,How to Start a Business,/course/how-to-start-a-business/,True,956,4.10000,4.10738,4.10738,52,False,104,0,2011-09-06T22:32:57Z,2011-10-12T17:21:40Z,455.0,INR,₹455,3200.0,INR,"₹3,200"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13000,3479860,بث يوم الجمعة 5 سبتمبر,/course/5-vqqeyl/,True,5,4.00000,4.00000,4.00000,1,False,5,0,2020-09-06T17:55:07Z,2020-09-07T11:33:24Z,NaN,NaN,NaN,2240.0,INR,"₹2,240"
11472,3481686,FOREX Metatrader4 - Guide to using the Mobile ...,/course/metatrader4-on-the-mobile-device/,True,0,0.00000,0.00000,0.00000,0,False,15,0,2020-09-07T12:24:22Z,2020-09-08T21:12:24Z,455.0,INR,₹455,5440.0,INR,"₹5,440"
11080,3482886,Forex Online Course - Beginners / Intermediate...,/course/forex-online-course-2020-telegramfx/,True,0,0.00000,0.00000,0.00000,0,False,19,0,2020-09-07T21:02:55Z,2020-09-09T02:24:43Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
11761,3485052,Trading Trend Like A Pro : Perfect Strategy fo...,/course/trading-trend-like-a-pro-perfect-strat...,False,314,0.00000,0.00000,0.00000,0,False,7,0,2020-09-08T17:58:00Z,2020-09-09T04:21:55Z,NaN,NaN,NaN,NaN,NaN,NaN
11269,3486006,CBBF (BTA - CERTIFIED BLOCKCHAIN BUSINESS FOUN...,/course/blockchainfoundation/,True,0,0.00000,0.00000,0.00000,0,False,0,2,2020-09-09T04:30:16Z,2020-09-10T06:31:11Z,NaN,NaN,NaN,1280.0,INR,"₹1,280"